### ISSUE TITLE
Exclusion criteria not fully showing in print

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-search-print#49]
### Issue description
From the CIS on 10/5: for a specific trial selected for print, parts of the exclusion criteria are not appearing.

> Our staff noticed a discrepancy between the ct.gov summary and the print version of a trial (NCT04224272) from cancer.gov.  Who is the best person to report such things? In this case, the print version omits the time frame in which specified agents are prohibited prior to entering the trial. This results in a very different exclusion criteria: not allowing something at all versus not allowing it within 3 weeks. I thought David and Sandy might appreciate seeing more specific criteria and how it is structured- this one including not just specific agents, but also a time frame. 
**The details are as follows.** 
https://clinicaltrials.gov/ct2/show/NCT04224272
_In exclusion criteria:_
•	Prior treatment with trastuzumab, pertuzumab, lapatinib, T-DM1, or other anti-HER2-targeted therapy </= 3 weeks before the first dose of ZW25
•	Prior treatment with chemotherapy, other anti-cancer therapy not otherwise specified, or hormonal cancer therapy </= 3 weeks before the first dose of ZW25
_When printed from cancer.gov (in conflict with the Inclusion Criteria):_   
Exclusion Criteria
•       Prior treatment with trastuzumab, pertuzumab, lapatinib, T-DM1, or other anti-HER2-targeted therapy 
•       Prior treatment with chemotherapy, other anti-cancer therapy not otherwise specified, or hormonal cancer therapy
https://www.cancer.gov/CTS.Print/Display?printid=bfffd248-d504-eb11-8185-0050568e168e
**The trial is correct until you choose to print it:  https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/v?id=NCI-2020-02983&loc=0&rl=2&tid=NCT04224272**

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Search for NCT04224272
2.  Look at the trial description page and note that in exclusion criteria, the correct criteria with "</= 3 weeks before the first dose of ZW25" is included
3.  Select the trial for print from the search results page, and look at the print display
4. Note that the criteria is missing "</= 3 weeks before the first dose of ZW25" does not appear on the print page

### What's the expected result?
</= 3 weeks before the first dose of ZW25 should appear on the print page - could we be stripping the special characters or somehow truncating the exclusion/inclusion results?

### What's the actual result?
Content in the exclusion/inclusion criteria is being truncated in the CTS print page

### Additional Information/Screenshots
**On the Trial Description Page:** 
![image](https://user-images.githubusercontent.com/31222859/95116443-0be1ff00-0715-11eb-85a7-223997e89852.png)

**On the Print Page:**
![image](https://user-images.githubusercontent.com/31222859/95116385-f2d94e00-0714-11eb-981f-85b2e0b2da3a.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairl-nih** [comment]
Closed by 875c3388cff4a704d74f37085b8e5b379d1e785b
