### ISSUE TITLE
Enabler: Create a deploy script

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-search-print#52]
# Create a deploy script.

We need a simple "run this script" for deploying.

> **ESTIMATE** TBD

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Sub-Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by blairl-nih** [comment]
No repository changes.  Script is stored elsewhere.

**Comment by blairlearn** [comment]
deploy script based on [API CreateAPISite script](https://github.com/NCIOCPL/webapi-tools/blob/master/build-tools/CreateAPISite.ps1)
