### ISSUE TITLE
Trial order in search results doesn't match the Print page

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-search-print#58]
### Issue description

The order in which trials are displayed in the Print page (on Blue) are not the same order as the trials are displayed in CTS Search Results page (except Page#1)

> **ESTIMATE** TBD

### Steps to reproduce the issue
1. Go to the CTS Basic Search Form on the local host 
2. Click the "Find Trials" button to perform default search)
3. We should land to the CTS Search Results page
4. Now we are in Page#1 of CTS Search Results page
5. Select all trials by checking the "Select all on page"
6. Click the "Print Selected" button
7. We should be redirected to the Print page (on Blue)
8. Compare the order in which trials are displayed in the Print page (on Blue) with the trials that are displayed in CTS Search Results page (on Blue)
9. Notice that the order in which trials are displayed in the Print page (on Blue) is the same as the trials are displayed in CTS Search Results page
10. Repeat Step#1 to Step#3
11. Select Page#4 from the pager
12. Repeat Step#5 to Step#8
13. Notice that the order in which trials are displayed in the Print page (on Blue) are not the same order as the trials are displayed in CTS Search Results page
14. From the screen-shot we can see that the trial that is displayed in the 3rd position on the CTS Search Results page is being displayed in the 2nd position on the Print page (on Blue)

### What's the expected result?
- The order in which trials are displayed in the Print page (on Blue) should be the same as the trials are displayed in CTS Search Results page

### What's the actual result?
-  The order in which trials are displayed in the Print page (on Blue) are not in the same order as the trials are displayed in CTS Search Results page

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/162487096-8a2e6401-8a01-4c99-b22a-06479f905548.png)

### Related Tickets
* Issue #9999
* Issue #9999

CC: @blairl-nih , @sarinapadilla , @SupriyaSaxena0605

**Comment by blairlearn** [comment]
Thoughts...
- Could it be the API returning trials in a random order?
- Could it be the APP passing trial IDs in a random order?

Check for API returns the same data in 10 iterations
```bash
for ((i=1; i<10; i++))
do
    curl -X POST "https://clinicaltrialsapi.cancer.gov/api/v2/trials" -H "accept: */*" -H "X-API-KEY: API_KEY_GOES_HERE!!" -H "Content-Type: application/json" -d "{\"nci_id\":[\"NCI-2014-01507\",\"NCI-2015-00054\",\"NCI-2015-00128\",\"NCI-2018-03695\",\"NCI-2016-01041\",\"NCI-2019-07439\",\"NCI-2019-01068\",\"NCI-2019-06124\",\"NCI-2018-02107\",\"NCI-2016-01417\"]}" --compressed -o output-$i;
    sleep 10;
done
```
