### ISSUE TITLE
Incorrect URL when emailing "classic" print pages.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-search-print#71]
### Issue description
When print pages generated by the legacy system are emailed, the link is missing the file path.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Find a print ID value which predates the new CTS.Print (e.g. on Dev, `DEA341F9-FF2C-EC11-82F6-0050568E76B3`)
2. Go to the print display path (e.g. `https://www-blue-dev.cancer.gov/CTS.Print/Display?printID=DEA341F9-FF2C-EC11-82F6-0050568E76B3`)
3. Click the "E-Mail These Results" link

### What's the expected result?
- A new email message will be created, including a link to the page.
- The URL for the page should include the path. (e.g. `https://www-blue-dev.cancer.gov/CTS.Print/Display?printID=DEA341F9-FF2C-EC11-82F6-0050568E76B3`)

### What's the actual result?
- No email is created. (Missing
- The path is missing (e.g. `https://www-blue-dev.cancer.gov/DEA341F9-FF2C-EC11-82F6-0050568E76B3`)

**Comment by alinai** [comment]
@sarinapadilla , can you please test it for me as I get account set up option on clicking the "Email" link on Print page and the "Email" button on the view page?

**Comment by sarinapadilla** [comment]
@alinai yes this is correct. It's just Windows not being able to resolve an email client. As long as the URL is mailto: it is the expected behavior. It looks good to me!

**Comment by alinai** [comment]
@sarinapadilla , Thanks for verifying this one. Really appreciate it!!
