### ISSUE TITLE
Missing CSS and JS assets on legacy print pages

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-search-print#72]
### Issue description
When print pages generated by the legacy system are displayed on the lower tiers, they reference CSS and JavaScript files which are not available.  These files will be available on production (served from Akamai NetStorage), but in the meantime, this interferes with testing.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Find a print ID value which predates the new CTS.Print (e.g. on Dev, `DEA341F9-FF2C-EC11-82F6-0050568E76B3`)
2. Open the F12 tools.
3. Go to the print display path (e.g. `https://www-blue-dev.cancer.gov/CTS.Print/Display?printID=DEA341F9-FF2C-EC11-82F6-0050568E76B3`)

### What's the expected result?
- All CSS and JavaScript files are retrieved.

### What's the actual result?
- 404 status returns for all CSS and JavaScript.

**Comment by alinai** [comment]
Getting the following error on refreshing the Print page:
![image](https://user-images.githubusercontent.com/28455973/181652495-431bc8ac-c1c9-40fe-afa1-f2dc1a466f3f.png)

**Comment by sarinapadilla** [comment]
@alinai that error is not something we are going to address for launch. I'll create a ticket for investigation later.
