### ISSUE TITLE
Trials with Trial Type "Other" should display "Not provided by clinicaltrials.gov"

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-print#74]
### Issue description
The print page for a trial description displays "Other" as the trial type for trials that return primary_purpose: "OTHER". This needs to be updated to say "Not provided by clinicaltrials.gov"

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Go to https://ncigovcdode450.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/r?loc=0&rl=2&st=C2989&t=C2991
2. Select the trial
3. Click on the "print selected"

### What's the expected result?
Trial Type is "Not provided by clinicaltrials.gov"

### What's the actual result?
Trial Type is "Other"

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by alinai** [comment]
Looks good on blue. Thanks @blairlearn

**Comment by sarinapadilla** [comment]
Looking good to me as well!
