### ISSUE TITLE
State is not appearing in Search Criteria box

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-print#75]
### Issue description
If you use a US state as part of your search criteria, then select a trial to print, the state parameter and name are not displaying in the Search Criteria box.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Go to https://ncigovcdode450.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/r?lcnty=United%20States&loc=2&lst=AL&rl=2
2. Select a trial
3. Print

### What's the expected result?
- Alabama should show as the value for the State parameter in the Search Criteria box.

### What's the actual result?
- The state parameter and Alabama should display in the Search Criteria box.

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment]
This is due to an ambiguity in [the specification for the list of states](https://github.com/NCIOCPL/clinical-trials-search-app/blob/develop/src/constants/index.js#L77).

CTS.Print is expecting a list of state codes.  What's being passed is a list of objects.

**Comment by blairlearn** [comment]
The workaround/quick fix is to parse out just the state abbreviations and ignore the rest of the structure. This feels somewhat dirty, but has the benefit of removing the need to sanitize the full names.

**Comment by alinai** [comment]
@blairlearn , @sarinapadilla , "Other treatments" also does NOT display in the Search Criteria box on the Print page. 
Steps to reproduce:
1. Go to https://ncigovcdode450.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/r?d=C471&i=C16032&lcnty=United%20States&loc=2&lst=AK&rl=2
2. Select a trial
3. Print.
4. See that the Search Criteria box on the Print page does not display "Other treatments"

**Comment by alinai** [comment]
Both "state" and "other treatments" are appearing on the Print page on blue.

![image](https://user-images.githubusercontent.com/28455973/182173913-a6a5235a-8809-4c7e-b0f1-d7a814b062ee.png)

**Comment by sarinapadilla** [comment]
This looks good to me!
