### ISSUE TITLE
"Other Treatment" is not appearing in search criteria box

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-search-print#76]
### Issue description
If the search criteria includes an entry in the "Other Treatment" field, the generated print page will not include it in the search criteria page.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Go to https://ncigovcdode450.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/r?i=C15313&lcnty=United%20States&loc=2&lst=MD&rl=2
2. Select a trial
3. Print

### What's the expected result?
- The print page should include the criterion: "Other Treatments: Radiation Therapy"

### What's the actual result?
- "Other Treatments" is missing.

### Additional details / screenshot
- Expected: ![image](https://user-images.githubusercontent.com/21063180/181771964-026129a1-135f-4282-a6e7-65789f7a487b.png)
- Actual: 
![image](https://user-images.githubusercontent.com/21063180/181772187-42cf6f7b-fadd-4474-a09c-60b2c9a0e50c.png)

**Comment by alinai** [comment]
Looks good on ODE450. Thanks @blairlearn!

**Comment by sarinapadilla** [comment]
Looking good to me as well!
