### ISSUE TITLE
Print requests with State parameter are stripping out all locations for display

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-print#84]
### Issue description
When performing a search for trials including the State parameter and then trying to print selected trials, all of the locations are removed from the display. This issue only happens when the State parameter is used - the Country and City parameters still filter locations correctly.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/v?a=60&id=NCI-2021-06445&lcnty=United%20States&loc=2&lst=CA&rl=2&t=C27814&tt=treatment and note that locations (including nearby) are displayed
3. Go to https://www.cancer.gov/CTS.Print/Display?printid=e3ea2c41-261d-ed11-82d6-0ed908919b64

### What's the expected result?
- The locations should display on the print page.

### What's the actual result?
- There are no locations displayed on the print page.

### Additional Screenshots
View page:
<img width="861" alt="Screen Shot 2022-08-23 at 12 09 34 PM" src="https://user-images.githubusercontent.com/24591940/186208090-0d314bb4-8668-4426-8397-b38aea9d02b4.png">

Print page:
<img width="1121" alt="Screen Shot 2022-08-23 at 12 09 47 PM" src="https://user-images.githubusercontent.com/24591940/186208236-83546d58-05b3-4968-be59-cb517d5235a0.png">

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment]
This is related to #75 and the same problem of CTS.Print expecting a list of state codes while the application is passing a list of objects with both an abbreviation and a name.

**Comment by SupriyaSaxena0605** [comment]
This issue looks good on ODE. Thanks @blairlearn

**Comment by blairlearn** [comment]
Fixed in 5ebb08d0f05c2c6dfe13bed1a85df7a5f50a9b61
